### ISSUE TITLE
Error on Login for some Players on 1.19.4

### ISSUE THREAD

**Issue by CloudeLecaw** [TeamKun/Wraith#2]
[11:01:03] [Server thread/INFO]: Joined: bastirusti95 | Brands: [vanilla] | GameMode: SURVIVAL | World: world | /ww spectate bastirusti95 | UUID: ed5cd822-7e3b-417e-b80a-94371e6e888a | IP: /93.205.241.250:50135 
[11:01:07] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[11:01:07] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[11:01:07] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[11:01:07] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[11:01:07] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[11:01:07] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)

Wraith 2.3.5   LoneLibs_1.0.24   Server: Paper 1.19.4

**Comment by CloudeLecaw** [comment]
```
[01:12:43 WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[01:12:43 WARN]: 	
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[01:12:43 WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```
